image: gradle:alpine

variables:
  PREPARE_JOBID: ""

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle assemble
  rules:
    - if: '$CI_COMMIT_TAG == null'

check:
  stage: test
  script: gradle check
  rules:
    - if: '$CI_COMMIT_TAG == null'

test:
  stage: test
  script: gradle test
  rules:
    - if: '$CI_COMMIT_TAG == null'

prepare:
  stage: deploy
  script:
    - echo "Preparing GitLab snapshot release..."
    - gradle assembleDist
    - cp build/distributions/*.zip game.zip
    - $PREPARE_JOBID = $CI_JOB_ID
  artifacts:
    paths:
      - game.zip

release:
  stage: deploy
  script:
    - echo "Creating GitLab snapshot release..."
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  release:
    name: "Release SNAPSHOT $(date +'%Y-%m-%d %H:%M:%S')"
    description: 'Rolling snapshot'
    tag_name: "Release_${CI_JOB_ID}"
    assets:
      links:
        - name: 'Release package (Linux/Windows)'
          url: https://szofttech.inf.elte.hu/szofttech-c-2023/group-05/citybuilder/-/jobs/${PREPARE_JOBID}/artifacts/raw/game.zip
  rules:
    - if: '$CI_COMMIT_TAG == null'