image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle assemble

test:
  stage: test
  script: gradle check

deploy:
  stage: deploy
  script:
    - echo "Deploying the game..."
    # Add your deployment script or commands here to deploy the game.
    # For example, you could copy the generated JAR file to a server or execute specific deployment steps.
    # Replace the echo command with your actual deployment commands.
    - cp build/libs/*.jar game.jar

  artifacts:
    paths:
      - game.jar

release:
  stage: deploy
  script:
    - echo "Creating GitLab snapshot release..."
    - gitlab-release create --name "Game Release" --tag-name "v${CI_COMMIT_TAG}" --description "SNAPSHOT release of the game" game.jar

