package model.buildings;

import model.Coordinate;
import model.Person;

import java.awt.*;
import java.util.ArrayList;

/**
 * This class represents a building that is generated by the game.
 */
public abstract class GeneratedBuilding extends Building {
    protected ArrayList<Person> people;
    protected SaturationRate saturationRate;
    protected int publicSafety;

    /**
     * Constructor of the generated building
     * @param texture is the texture of the building
     * @param coords is the coordinates of the building
     * @param firePossibility is the fire possibility of the building
     * @param isOnFire is the building on fire
     * @param people is the people in the building
     * @param saturationRate is the saturation rate of the building
     * @param publicSafety is the public safety of the building
     */
    public GeneratedBuilding(Image texture, Coordinate coords, double firePossibility, boolean isOnFire, ArrayList<Person> people, SaturationRate saturationRate, int publicSafety) {
        super(texture, coords, firePossibility, isOnFire);
        this.people = people;
        this.saturationRate = saturationRate;
        this.publicSafety = publicSafety;
    }

    /**
     * Get the people in the building
     * @return the people in the building
     */
    public ArrayList<Person> getPeople() {
        return people;
    }

    /**
     * Set the people in the building
     * @param people is the people in the building
     */
    public void setPeople(ArrayList<Person> people) {
        this.people = people;
    }

    /**
     * Get the saturation rate of the building
     * @return the saturation rate of the building
     */
    public SaturationRate getSaturationRate() {
        return saturationRate;
    }

    /**
     * Set the saturation rate of the building
     * @param saturationRate is the saturation rate of the building
     */
    public void setSaturationRate(SaturationRate saturationRate) {
        this.saturationRate = saturationRate;
    }

    /**
     * Get the public safety of the building
     * @return the public safety of the building
     */
    public int getPublicSafety() {
        return publicSafety;
    }

    /**
     * Set the public safety of the building
     * @param publicSafety is the public safety of the building
     */
    public void setPublicSafety(int publicSafety) {
        this.publicSafety = publicSafety;
    }
}
